name: torchtree
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.7
  - treezy
  - pytorch>=1.9
  - pip
# Dev dependencies
  - black=23.3.0
  - docformatter
  - flake8
  - isort
  - pre-commit
  - pytest
